try:
  from .face_recognizer import FaceRecognizer
except Exception as e:
  print(e)
from .ultra_face_inference import UltraFaceInference
